# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-31 06:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='电影名')),
                ('info', models.CharField(max_length=1024, verbose_name='电影简介')),
                ('on_time', models.DateTimeField(verbose_name='上映时间')),
                ('poster', models.ImageField(upload_to='upload', verbose_name='海报')),
                ('head_image', models.ImageField(upload_to='upload', verbose_name='电影封面')),
                ('score', models.FloatField(default=0.0, verbose_name='评分')),
                ('marked_members', models.IntegerField(default=0, verbose_name='评分人数')),
                ('commented_member', models.IntegerField(default=0, verbose_name='评论人数')),
                ('active', models.BooleanField(default=True, verbose_name='情况')),
                ('isOnScreen', models.BooleanField(default=True, verbose_name='是否上映')),
            ],
            options={
                'verbose_name': '电影',
                'verbose_name_plural': '电影',
            },
        ),
        migrations.CreateModel(
            name='FilmComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1024, verbose_name='评论内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('active', models.BooleanField(default=True, verbose_name='情况')),
            ],
            options={
                'verbose_name': '短影评',
                'verbose_name_plural': '短影评',
            },
        ),
        migrations.CreateModel(
            name='FilmReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('subtitle', models.CharField(max_length=50, verbose_name='副标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('commented_members', models.IntegerField(default=0, verbose_name='评论人数')),
                ('hits', models.IntegerField(default=0, verbose_name='点击量')),
                ('thumbnail', models.ImageField(upload_to='upload', verbose_name='缩略图')),
                ('active', models.BooleanField(default=True, verbose_name='情况')),
            ],
            options={
                'verbose_name': '长影评',
                'verbose_name_plural': '长影评',
            },
        ),
        migrations.CreateModel(
            name='FilmReviewComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1024, verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('active', models.BooleanField(default=True, verbose_name='情况')),
            ],
            options={
                'verbose_name': '影评评论',
                'verbose_name_plural': '影评评论',
            },
        ),
        migrations.CreateModel(
            name='FilmReviewGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isGood', models.BooleanField(default=False, verbose_name='是否点赞')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
            ],
            options={
                'verbose_name': '点赞',
                'verbose_name_plural': '点赞',
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='分值')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Api.Film', verbose_name='评分电影')),
            ],
            options={
                'verbose_name': '评分',
                'verbose_name_plural': '评分',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='新闻标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('hits', models.IntegerField(default=0, verbose_name='点击量')),
                ('active', models.BooleanField(default=True, verbose_name='情况')),
                ('goodNum', models.IntegerField(default=0, verbose_name='点赞数')),
                ('commented_members', models.IntegerField(default=0, verbose_name='评论人数')),
                ('picture', models.ImageField(upload_to='upload', verbose_name='图片')),
            ],
            options={
                'verbose_name': '新闻',
                'verbose_name_plural': '新闻',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='NewsComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1024, verbose_name='内容')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='评论时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('active', models.BooleanField(default=True, verbose_name='情况')),
            ],
            options={
                'verbose_name': '新闻评论',
                'verbose_name_plural': '新闻评论',
                'ordering': ['create_time'],
            },
        ),
        migrations.CreateModel(
            name='NewsGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isGood', models.BooleanField(default=False, verbose_name='是否点赞')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
            ],
            options={
                'verbose_name': '点赞',
                'verbose_name_plural': '点赞',
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=10, unique=True, verbose_name='标签')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='None', max_length=20, verbose_name='用户ID')),
                ('nickName', models.CharField(blank=True, default='None', max_length=20, null=True, verbose_name='昵称')),
                ('password', models.CharField(blank=True, default='None', max_length=100, null=True, verbose_name='密码')),
                ('registerTime', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='注册时间')),
                ('authSession', models.CharField(blank=True, default='000000', max_length=30, null=True, verbose_name='Session')),
                ('email', models.CharField(blank=True, default='None', max_length=100, null=True, verbose_name='邮箱')),
                ('headImage', models.ImageField(default='default/1.png', upload_to='headImages', verbose_name='头像')),
                ('changePwdCode', models.CharField(blank=True, default='None', max_length=5, null=True, verbose_name='验证码')),
                ('checkCode', models.CharField(blank=True, default='None', max_length=6, null=True, verbose_name='验证码')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'get_latest_by': 'registerTime',
            },
        ),
        migrations.AddField(
            model_name='newsgoods',
            name='fromUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Api.User', verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='newsgoods',
            name='toNews',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Api.News', verbose_name='新闻'),
        ),
        migrations.AddField(
            model_name='newscomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Api.User', verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='newscomment',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Api.News', verbose_name='新闻'),
        ),
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Api.User', verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='mark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Api.User', verbose_name='评分人'),
        ),
        migrations.AddField(
            model_name='filmreviewgoods',
            name='fromUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Api.User', verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='filmreviewgoods',
            name='toNews',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Api.Film', verbose_name='影评'),
        ),
        migrations.AddField(
            model_name='filmreviewcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Api.User', verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='filmreviewcomment',
            name='film_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Api.FilmReview', verbose_name='影评'),
        ),
        migrations.AddField(
            model_name='filmreview',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Api.User', verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='filmreview',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Api.Film', verbose_name='电影'),
        ),
        migrations.AddField(
            model_name='filmcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Api.User', verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='filmcomment',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Api.Film', verbose_name='电影'),
        ),
        migrations.AddField(
            model_name='film',
            name='tag',
            field=models.ManyToManyField(to='Api.Tags', verbose_name='标签'),
        ),
    ]
